# /opt/jenkins/docker-compose.yml
services:
  jenkins:
    build: .
    container_name: jenkins
    restart: unless-stopped
    user: "1000:1000"                    # utilisateur non-root
    # Si tu n'accèdes à Jenkins QUE via Caddy, tu peux supprimer ces ports.
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "999"                            # garde le GID adéquat
    networks:
      - dev-net
    environment:
      # Préfixe sous-chemin pour Jenkins
      JENKINS_OPTS: "--prefix=/jenkins"
      # JVM + compat reverse proxy (garde ta mémoire et ajoute la compat)
      JAVA_OPTS: "-Xms512m -Xmx4g -Djenkins.model.Jenkins.crumbIssuerProxyCompatibility=true"

volumes:
  jenkins-home:

networks:
  dev-net:
    external: true

