services:
  caddy:
    image: caddy:2
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - dev-net
      - monitoring_monitoring
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  caddy_data:
  caddy_config:

networks:
  dev-net:
    external: true
  monitoring_monitoring:
    external: true

