global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # Prometheus lui-même
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Node Exporter (métriques OS)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # STT (ton serveur instrumenté /metrics)
  - job_name: "stt"
    metrics_path: /metrics
    static_configs:
      - targets: ["stt:8090"]   # ← adapte si STT_PORT ≠ 8090

  # TTS (exporter interne)
  - job_name: "tts"
    metrics_path: /metrics
    static_configs:
      - targets: ["tts:9401"]

  # GPU via NVIDIA DCGM
  - job_name: "dcgm"
    static_configs:
      - targets: ["dcgm-exporter:9400"]

  # Qdrant - métriques natives
  - job_name: 'qdrant'
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ['qdrant:6333']

  # vLLM - métriques natives (/metrics sur le port vLLM)
  - job_name: "vllm"
    metrics_path: /metrics
    static_configs:
      - targets: ["llm:8000"]   # ← adapte si VLLM_PORT ≠ 8000

  # MCP (interne)
  - job_name: "mcp-internal"
    metrics_path: /metrics
    static_configs:
      - targets: ["viona-mcp-internal:9411"]

  # MCP (externe)
  - job_name: "mcp-teacher"
    metrics_path: /metrics
    static_configs:
      - targets: ["viona-mcp-teacher:9411"]

  # Cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Whisper
  - job_name: "whisper"
    static_configs:
      - targets: ["whisper:9109"]
        labels:
          app: whisper
rule_files:
  - /etc/prometheus/rules/*.yml
